### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by chenxluo** [Aleiluo/danbooruTagEditor#1]
报错如下
`PS D:\danbooruTagEditor\danbooruTagEditor> python GUI.py
Traceback (most recent call last):
  File "D:\danbooruTagEditor\danbooruTagEditor\GUI.py", line 92, in <module>
    window = EditorGUI()
  File "D:\danbooruTagEditor\danbooruTagEditor\GUI.py", line 31, in __init__
    super().__init__()
  File "D:\danbooruTagEditor\danbooruTagEditor\scripts\TagTran.py", line 6, in __init__
    super().__init__()
  File "D:\danbooruTagEditor\danbooruTagEditor\scripts\WorkingFlow.py", line 15, in __init__
    super().__init__()
  File "D:\danbooruTagEditor\danbooruTagEditor\scripts\TagFilter.py", line 13, in __init__
    super().__init__()
  File "D:\danbooruTagEditor\danbooruTagEditor\scripts\UserEvents.py", line 81, in __init__
    self.left_region = QRegion(0, 0, self.width() * 3 / 7, self.height())
TypeError: arguments did not match any overloaded call:
  QRegion(): too many arguments
  QRegion(x: int, y: int, w: int, h: int, type: QRegion.RegionType = QRegion.Rectangle): argument 3 has unexpected type 'float'
  QRegion(r: QRect, type: QRegion.RegionType = QRegion.Rectangle): argument 1 has unexpected type 'int'
  QRegion(a: QPolygon, fillRule: Qt.FillRule = Qt.OddEvenFill): argument 1 has unexpected type 'int'
  QRegion(bitmap: QBitmap): argument 1 has unexpected type 'int'
  QRegion(region: QRegion): argument 1 has unexpected type 'int'
  QRegion(variant: Any): too many arguments`
python版本为3.10.8

**Comment by Aleiluo** [comment]
已修复
